#!/usr/bin/env python3
"""
make_kael_no_push.py

Similar to make_kael_canonical.py but does NOT push to remote. It will create directories, copy files, write templates and commit locally only.

Usage:
  python3 scripts/make_kael_no_push.py [--branch main] [--yes]
"""
from pathlib import Path
import subprocess
import argparse
import sys

# Reuse the same templates as the main script expects to find in repo
from datetime import datetime

GALLERY_TEMPLATE = """# Kael — image gallery\n\nThis file was generated by make_kael_no_push.py on {date}\n\nSee Kael/IMAGE_METADATA.md for metadata placeholders.\n"""


def run(cmd):
    subprocess.check_call(cmd, shell=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--branch", default="main")
    parser.add_argument("--yes", action="store_true")
    args = parser.parse_args()

    repo_root = Path.cwd()
    kael_images = repo_root / "Kael" / "images"
    canonical_dir = kael_images / "canonical"
    variants_dir = kael_images / "variants"

    files_to_move = ["Kael_1.png","Kael_2.png","Kael_3.png","Kael_4.png"]

    if not args.yes:
        ans = input("This will copy images to Kael/images/canonical/ and commit locally. Continue? [y/N] ")
        if ans.lower() not in ("y","yes"):
            print("Aborted")
            sys.exit(0)

    canonical_dir.mkdir(parents=True, exist_ok=True)
    variants_dir.mkdir(parents=True, exist_ok=True)

    moved = []
    for f in files_to_move:
        src = kael_images / f
        dst = canonical_dir / f
        if src.exists():
            print(f"Copying {src} -> {dst}")
            content = src.read_bytes()
            dst.write_bytes(content)
            moved.append(str(dst.relative_to(repo_root)))
        else:
            print(f"Warning: {src} not found, skipping")

    # write minimal gallery and metadata placeholders if they don't exist
    meta_file = repo_root / "Kael" / "IMAGE_METADATA.md"
    gallery_file = repo_root / "Kael" / "gallery.md"

    if not meta_file.exists():
        meta_file.write_text("# IMAGE_METADATA placeholder (fill after renders)\n", encoding='utf-8')
        print("Wrote", meta_file)
    else:
        print("Metadata file exists; not overwriting:", meta_file)

    if not gallery_file.exists():
        gallery_file.write_text(GALLERY_TEMPLATE.format(date=datetime.utcnow().isoformat()), encoding='utf-8')
        print("Wrote", gallery_file)
    else:
        print("Gallery file exists; not overwriting:", gallery_file)

    # git add and commit locally only
    try:
        run('git add Kael/IMAGE_METADATA.md Kael/gallery.md')
        for p in moved:
            run(f'git add "{p}"')
        run('git commit -m "Mark Kael canonical images + metadata placeholders (local commit, no push)"')
        print('Committed locally. No push performed.')
    except subprocess.CalledProcessError as e:
        print('Git error:', e)
        print('You may need to run git add/commit manually.')

if __name__ == '__main__':
    main()
